import Head from 'next/head'
import { useState } from 'react'
import { gql, useQuery } from '@apollo/client'
import AnimalResults from '../components/Animals/AnimalResults'
import EntryInterview from '../components/EntryInterview'
import { useRouter } from 'next/router'
import AnimalResultsContainer from '../containers/AnimalResults'

const animalsGql = gql`
  query AnimalsQuery($location: String, $page: Int) {
    animals(location: $location, page: $page, limit: 20) {
      animals {
        name
        photos {
          medium
        }
        url
      }
    }
  }
`

const useAnimalsQuery = (location: string, page: number) => {
  if (process.env.NODE_ENV === 'development') {
    const mockAnimals = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].reduce((acc, curr) => {
      acc.push({
        photos: [
          {
            medium:
              'https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/322868_1100-800x825.jpg',
          },
        ],
        name: `Dog ${curr}`,
        url: 'https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/322868_1100-800x825.jpg',
      })
      return acc
    }, [])
    return { data: { animals: { animals: mockAnimals } }, loading: true }
  } else {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    return useQuery(animalsGql, {
      variables: {
        location,
        page,
      },
      skip: !location,
    })
  }
}

export default function Home(props) {
  const [initialLocation] = useState(props.location || '')
  const router = useRouter()

  const location = router ? router.query.location : initialLocation

  return (
    <div className="tw-h-fit tw-py-4">
      <Head>
        <title>Dog Search App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {location && (
        <h2 className="tw-text-2xl tw-font-bold tw-text-black tw-mb-4">
          Viewing Pets near {location}
        </h2>
      )}
      <main className="tw-flex tw-justify-center">
        {!location && (
          <EntryInterview
            onSubmit={({ location: newLoc }) => {
              router.push(`/?location=${newLoc}`, undefined, {
                shallow: true,
              })
            }}
          />
        )}
        {location && <AnimalResultsContainer location={location} />}
      </main>
    </div>
  )
}

export const getServerSideProps = ({ query }) => {
  const location = (query && query.location) || null
  return {
    props: {
      location,
    },
  }
}
